export const ProgramDummy = [
  {
    id: 101,
    program_status: "open",
    program_name: "Web Development Bootcamp Intensif",
    major_name: "Teknik Informatika",
    type_sesi: "Online",
    description:
      "Program intensif selama 3 bulan untuk menguasai Full-Stack Web Development, mulai dari front-end (React) hingga back-end (Node.js & Express). Cocok untuk pemula.",
    image_url: "https://example.com/images/webdev_intensive.jpg",
    start_date: "2025-01-15T00:00:00Z",
    campus_name: "Kampus Digital Jakarta",
    capacity: 50,
    online_link: "https://meet.google.com/abc-defg-hij",
    offline_address: null,
    visibility: "public",
  },
  {
    id: 102,
    program_status: "closed",
    program_name: "Data Science Masterclass",
    major_name: "Statistika",
    type_sesi: "Offline",
    description:
      "Pelatihan mendalam tentang analisis data, machine learning, dan visualisasi menggunakan Python dan R. Dilaksanakan di laboratorium data kampus.",
    image_url: "https://example.com/images/datascience_master.jpg",
    start_date: "2025-03-01T00:00:00Z",
    campus_name: "Kampus Teknologi Bandung",
    capacity: 30,
    online_link: null,
    offline_address: "Lab Data Gedung A, Lantai 3",
    visibility: "private",
  },
  {
    id: 103,
    program_status: "open",
    program_name: "UI/UX Design Thinking",
    major_name: "Desain Komunikasi Visual",
    type_sesi: "Online",
    description:
      "Mempelajari prinsip-prinsip desain antarmuka pengguna (UI) dan pengalaman pengguna (UX), termasuk proses design thinking, prototyping, dan testing.",
    image_url: "https://example.com/images/uiux_design.jpg",
    start_date: "2025-05-20T00:00:00Z",
    campus_name: "Kampus Kreatif Surabaya",
    capacity: 60,
    online_link: "https://zoom.us/j/1234567890",
    offline_address: null,
    visibility: "public",
  },
  {
    id: 104,
    program_status: "open",
    program_name: "Digital Marketing Strategy",
    major_name: "Manajemen Bisnis",
    type_sesi: "Offline",
    description:
      "Mengembangkan strategi pemasaran digital yang efektif, mencakup SEO, SEM, media sosial, dan email marketing. Fokus pada studi kasus bisnis nyata.",
    image_url: "https://example.com/images/digital_marketing.jpg",
    start_date: "2025-02-10T00:00:00Z",
    campus_name: "Kampus Bisnis Yogyakarta",
    capacity: 45,
    online_link: null,
    offline_address: "Ruang Seminar Gedung B, Lantai 1",
    visibility: "private",
  },
  {
    id: 105,
    program_status: "open",
    program_name: "Cloud Computing Essentials (AWS)",
    major_name: "Sistem Informasi",
    type_sesi: "Online",
    description:
      "Pengantar fundamental komputasi awan menggunakan platform Amazon Web Services (AWS). Mempersiapkan peserta untuk sertifikasi dasar.",
    image_url: "https://example.com/images/cloud_computing.jpg",
    start_date: "2025-07-01T00:00:00Z",
    campus_name: "Kampus Global Jakarta",
    capacity: 75,
    online_link: "https://teams.microsoft.com/l/meetup-join/...",
    offline_address: null,
    visibility: "public",
  },
];
